### ISSUE TITLE
[bug]Craft Takes Time server error 1.12.2

### ISSUE THREAD

**Issue by LonelyxiyaOVO** [jingshenSN2/CraftTakesTime#15]
Craft Takes Time
[crash-2024-09-29_11.45.57-server.txt](https://github.com/user-attachments/files/17178306/crash-2024-09-29_11.45.57-server.txt)

**Comment by jingshenSN2** [comment]
would you mind export and share the modpack you are using? I can't reproduce this locally with craft takes time alone, probably there's some conflicts with other mods in the modpack.

**Comment by LonelyxiyaOVO** [comment]
okay, hold on, please

**Comment by LonelyxiyaOVO** [comment]
[1.zip](https://github.com/user-attachments/files/17237946/1.zip)
if you need a config file, just say so!

**Comment by LonelyxiyaOVO** [comment]
i'm so stupid i actually sent you the client.....

**Comment by jingshenSN2** [comment]
haha, yeah, I guess this is a server bug, which gives me some idea of how to fix it. I am now able to reproduce this locally by starting a server.

**Comment by jingshenSN2** [comment]
I'm uploading a beta version now, would be great if you could help test this new version in your server pack.

**Comment by LonelyxiyaOVO** [comment]
don't worry, i'm always available

**Comment by LonelyxiyaOVO** [comment]
![image](https://github.com/user-attachments/assets/ff04c5e2-c8d2-41eb-9ade-1772d637c70c)
It should be fine. It's working fine.

**Comment by jingshenSN2** [comment]
great, let me close this issue.
