### ISSUE TITLE
Sounds are duplicated.

### ISSUE THREAD

**Issue by Mihail001** [jingshenSN2/CraftTakesTime#4]
If I click two times on the result of crufting sounds are duplicated. And if I use a recipe book click on the result of crufting it doesn't stop showing me how to craft it. And if I put a lot of items in the workbench it doesn't stop crafting a certain item, until you run out of items in  workbench. And if I use "OptiFine_1.16.5_HD_U_G7" craft in workbench doesn't duplicate many times. Maybe I didn't understand something, I am not sure.

https://user-images.githubusercontent.com/74407310/109542873-b3056f80-7ad6-11eb-8ecc-e04d303030be.mp4

I use: Minecraft: 1.16.5
Forge: 1.16.5-forge-36.0.42
CraftTime-FORGE-1.16.4-0.4.3.jar
(And your mod doesn't work good with mod [Crafting Station](https://www.curseforge.com/minecraft/mc-mods/crafting-station) Crafting Station's workbench hasn't got crafting time.)

**Comment by jingshenSN2** [comment]
1. sounds duplicate is a bug.
2. recipe book preview is a bug too.
3. not stop until run out of items is not a bug. it's a feature.
4. compatibility with other mod's crafting table is not very good. Only a few modded crafting tables are supported yet.
Thanks for reporting bugs~~

**Comment by Mihail001** [comment]
Thanks for your quick answer.
